// Code generated by interfacer; DO NOT EDIT

package gogit

import (
	"context"
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
)

// Worktree is an interface generated for "github.com/go-git/go-git/v5.Worktree".
type Worktree interface {
	Add(string) (plumbing.Hash, error)
	AddGlob(string) error
	AddWithOptions(*git.AddOptions) error
	Checkout(*git.CheckoutOptions) error
	Clean(*git.CleanOptions) error
	Commit(string, *git.CommitOptions) (plumbing.Hash, error)
	Grep(*git.GrepOptions) ([]git.GrepResult, error)
	Move(string, string) (plumbing.Hash, error)
	Pull(*git.PullOptions) error
	PullContext(context.Context, *git.PullOptions) error
	Remove(string) (plumbing.Hash, error)
	RemoveGlob(string) error
	Reset(*git.ResetOptions) error
	Status() (git.Status, error)
	Submodule(string) (*git.Submodule, error)
	Submodules() (git.Submodules, error)
}
