// Code generated by mockery v1.1.1. DO NOT EDIT.

package mocks

import (
	context "context"

	kube "github.com/argoproj-labs/argocd-autopilot/pkg/kube"
	kubernetes "k8s.io/client-go/kubernetes"

	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// Apply provides a mock function with given fields: ctx, namespace, manifests
func (_m *Factory) Apply(ctx context.Context, namespace string, manifests []byte) error {
	ret := _m.Called(ctx, namespace, manifests)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, namespace, manifests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// KubernetesClientSet provides a mock function with given fields:
func (_m *Factory) KubernetesClientSet() (kubernetes.Interface, error) {
	ret := _m.Called()

	var r0 kubernetes.Interface
	if rf, ok := ret.Get(0).(func() kubernetes.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubernetes.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KubernetesClientSetOrDie provides a mock function with given fields:
func (_m *Factory) KubernetesClientSetOrDie() kubernetes.Interface {
	ret := _m.Called()

	var r0 kubernetes.Interface
	if rf, ok := ret.Get(0).(func() kubernetes.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kubernetes.Interface)
		}
	}

	return r0
}

// Wait provides a mock function with given fields: _a0, _a1
func (_m *Factory) Wait(_a0 context.Context, _a1 *kube.WaitOptions) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *kube.WaitOptions) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
