// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package assets

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("../../assets", "README.md", "\"dGhpcyBpcyBoZXJlIGp1c3QgdG8gZml4IHRoaXMgaXNzdWU6IGh0dHBzOi8vZ2l0aHViLmNvbS9hcmdvcHJvai9hcmdvLWNkL2lzc3Vlcy8yOTA3\"")
	packr.PackJSONBytes("../../assets", "badge.svg", "\"bW9jaw==\"")
	packr.PackJSONBytes("../../assets", "builtin-policy.csv", "\"bW9jaw==\"")
	packr.PackJSONBytes("../../assets", "model.conf", "\"bW9jaw==\"")
	packr.PackJSONBytes("../../assets", "swagger.json", "\"Im1vY2si\"")
}
