// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GitopsClient is the client API for Gitops service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitopsClient interface {
	// Add a manifest to a gitops repository
	AddManifest(ctx context.Context, in *AddManifestRequest, opts ...grpc.CallOption) (*AddManifestResponse, error)
}

type gitopsClient struct {
	cc grpc.ClientConnInterface
}

func NewGitopsClient(cc grpc.ClientConnInterface) GitopsClient {
	return &gitopsClient{cc}
}

func (c *gitopsClient) AddManifest(ctx context.Context, in *AddManifestRequest, opts ...grpc.CallOption) (*AddManifestResponse, error) {
	out := new(AddManifestResponse)
	err := c.cc.Invoke(ctx, "/github.com.argoproj.argocd_autopilot.pkg.apis.gitops.v1.Gitops/AddManifest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitopsServer is the server API for Gitops service.
// All implementations must embed UnimplementedGitopsServer
// for forward compatibility
type GitopsServer interface {
	// Add a manifest to a gitops repository
	AddManifest(context.Context, *AddManifestRequest) (*AddManifestResponse, error)
	mustEmbedUnimplementedGitopsServer()
}

// UnimplementedGitopsServer must be embedded to have forward compatible implementations.
type UnimplementedGitopsServer struct {
}

func (UnimplementedGitopsServer) AddManifest(context.Context, *AddManifestRequest) (*AddManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddManifest not implemented")
}
func (UnimplementedGitopsServer) mustEmbedUnimplementedGitopsServer() {}

// UnsafeGitopsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitopsServer will
// result in compilation errors.
type UnsafeGitopsServer interface {
	mustEmbedUnimplementedGitopsServer()
}

func RegisterGitopsServer(s grpc.ServiceRegistrar, srv GitopsServer) {
	s.RegisterService(&Gitops_ServiceDesc, srv)
}

func _Gitops_AddManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitopsServer).AddManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.argoproj.argocd_autopilot.pkg.apis.gitops.v1.Gitops/AddManifest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitopsServer).AddManifest(ctx, req.(*AddManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gitops_ServiceDesc is the grpc.ServiceDesc for Gitops service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gitops_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.argoproj.argocd_autopilot.pkg.apis.gitops.v1.Gitops",
	HandlerType: (*GitopsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddManifest",
			Handler:    _Gitops_AddManifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apis/gitops/v1/gitops.proto",
}
