apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ../base

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - "server.insecure=true"
