// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AdoUrl is an autogenerated mock type for the AdoUrl type
type AdoUrl struct {
	mock.Mock
}

// GetProjectName provides a mock function with given fields:
func (_m *AdoUrl) GetProjectName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
